const $=id=>document.getElementById(id);
let token='',jobId=null,connected=false,polling=false;
const examples=[
'The city library extended its weekday hours from 6 p.m. to 9 p.m. Residents had asked for more study time after work. The new schedule is a three-month pilot, and staff will track attendance before deciding whether to keep it.',
'A local school installed solar panels on its roof this summer. The panels are expected to supply half of the building’s electricity. Students will use energy readings from the system in their science classes.',
'A neighborhood bakery will donate unsold bread to a nearby food bank every evening. Volunteers will collect the bread after closing. The partnership aims to reduce food waste and provide fresh food to families.',
'The regional rail service added two morning trains on its busiest route. The change follows passenger complaints about overcrowding. Officials will review ridership after six weeks.',
'A community garden opened on an unused parking lot. Residents can rent small plots to grow vegetables. A weekly workshop teaches beginners how to care for their plants.',
'The museum introduced free admission on Sunday mornings. Families can also join guided tours during those hours. The museum hopes the program will attract residents who have never visited.'
];
function samples(){$('inputs').value=examples.join('\n\n');}samples();$('sample').onclick=samples;
async function api(path,body){const r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error(r.status===401?'Invalid API token.':`Coordinator request failed (${r.status}).`);return r.json();}
function el(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
async function refresh(){if(polling||!connected)return;polling=true;try{const workers=await api('/workers?limit=100');const relevant=workers.filter(w=>w.supported_tasks.includes('summarization'));$('workers').replaceChildren();for(const w of relevant){const n=el('article',undefined,'worker');n.append(el('strong',w.name),el('span',w.status,'badge'),el('small',`${w.ram_gb} GB · ${w.cpu} · ${w.model_id}`));$('workers').append(n);}if(!relevant.length)$('workers').append(el('p','No summary workers registered. Start a worker on each Mac.'));$('online').textContent=`${relevant.filter(w=>w.status!=='OFFLINE').length} online`;
if(jobId){const data=await api(`/jobs/${jobId}/results`);$('status').textContent=data.status;$('progress').max=data.total_inputs;$('progress').value=data.completed_inputs+data.failed_inputs;$('job').textContent=`${data.completed_inputs}/${data.total_inputs} summaries · ${data.failed_inputs} failed · Job ${jobId}`;$('results').replaceChildren();for(const t of data.tasks){const n=el('article',undefined,'result');const result=data.results.find(r=>r.index===t.input_start_index);n.append(el('small',`PARAGRAPH ${t.input_start_index+1} · ${t.status}`),el('p',result?.text||'Waiting for a summary…'),el('small',`${t.worker_name||'Unassigned'}${t.execution_time_ms!==null?' · '+(t.execution_time_ms/1000).toFixed(1)+'s':''} · attempt ${t.attempt_count}`));$('results').append(n);}}$('error').textContent='';}catch(e){$('error').textContent=e.message;}finally{polling=false;}}
$('connect').onclick=async()=>{token=$('token').value;try{await api('/workers?limit=1');connected=true;$('connection').textContent='Connected';$('submit').disabled=false;await refresh();}catch(e){connected=false;$('submit').disabled=true;$('connection').textContent='Not connected';$('error').textContent=e.message;}};
$('submit').onclick=async()=>{const inputs=$('inputs').value.split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean);if(!inputs.length){$('error').textContent='Add at least one paragraph.';return;}$('submit').disabled=true;try{const j=await api('/jobs',{task_type:'summarization',inputs,optimization:'fastest'});jobId=j.job_id;await refresh();}catch(e){$('error').textContent=e.message;}finally{$('submit').disabled=!connected;}};
setInterval(refresh,2000);
